/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNINativeLeak */

#ifndef _Included_JNINativeLeak
#define _Included_JNINativeLeak
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNINativeLeak
 * Method:    allocateMemory
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNINativeLeak_allocateMemory
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
